import writeXlsxFile from "write-excel-file/browser";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import logoUrl from "@assets/FinVision360_Logo_H_(transparent)_1776714495394.png";

const BRAND: [number, number, number] = [28, 145, 212];
const DARK: [number, number, number] = [13, 58, 92];
const GRAY: [number, number, number] = [130, 130, 130];
const LIGHT_BG: [number, number, number] = [244, 250, 255];
const HEADER_H = 20;

export type ExportSheet = {
  name: string;
  columns: string[];
  rows: (string | number | null | undefined)[][];
};

export type ExportData = {
  filename: string;
  sheets: ExportSheet[];
};

async function loadLogoDataUrl(): Promise<string | null> {
  try {
    const res = await fetch(logoUrl);
    const blob = await res.blob();
    return await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

export function exportCSV(data: ExportData) {
  const lines: string[] = [];
  lines.push(`# FinVision360 — ${data.filename}`);
  lines.push(`# Generated: ${new Date().toLocaleString()}`);
  lines.push(`# finvision360.replit.app`);
  lines.push("");
  for (let i = 0; i < data.sheets.length; i++) {
    const sheet = data.sheets[i];
    if (data.sheets.length > 1) {
      if (i > 0) lines.push("");
      lines.push(`## ${sheet.name}`);
    }
    lines.push(sheet.columns.map(quoteCell).join(","));
    for (const row of sheet.rows) {
      lines.push(row.map((c) => quoteCell(String(c ?? ""))).join(","));
    }
  }
  download(
    new Blob([lines.join("\n")], { type: "text/csv;charset=utf-8;" }),
    `${data.filename}.csv`
  );
}

export async function exportExcel(data: ExportData): Promise<void> {
  type CellObj = { value: string | number | null };
  type RowData = CellObj[];

  const sheets = data.sheets.map((sheet) => {
    const sheetData: RowData[] = [
      [{ value: "FinVision360" }],
      [{ value: sheet.name }],
      [{ value: `Generated: ${new Date().toLocaleString()}` }],
      [],
      sheet.columns.map((col) => ({ value: col })),
      ...sheet.rows.map((r) =>
        r.map((c) => ({ value: c === null || c === undefined ? "" : c }))
      ),
    ];
    return { data: sheetData, sheet: sheet.name.slice(0, 31) };
  });

  const blob = await writeXlsxFile(sheets as any).toBlob();
  download(blob, `${data.filename}.xlsx`);
}

export async function exportPDF(data: ExportData): Promise<void> {
  const doc = new jsPDF({ orientation: "landscape" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  const logoDataUrl = await loadLogoDataUrl();

  const drawPageHeader = () => {
    if (logoDataUrl) {
      doc.addImage(logoDataUrl, "PNG", 7, 3, 42, 14);
    } else {
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...DARK);
      doc.text("FinVision360", 10, 13);
    }

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...DARK);
    doc.text(data.filename, pageW - 12, 12, { align: "right" });

    doc.setDrawColor(...BRAND);
    doc.setLineWidth(0.6);
    doc.line(7, HEADER_H, pageW - 7, HEADER_H);
  };

  drawPageHeader();
  let y = HEADER_H + 6;

  for (let i = 0; i < data.sheets.length; i++) {
    const sheet = data.sheets[i];

    if (data.sheets.length > 1) {
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...DARK);
      doc.text(sheet.name, 14, y);
      y += 6;
    }

    autoTable(doc, {
      startY: y,
      head: [sheet.columns],
      body: sheet.rows.map((r) => r.map((c) => String(c ?? ""))),
      styles: {
        fontSize: 8.5,
        cellPadding: 3,
        overflow: "linebreak",
        textColor: [30, 30, 30],
      },
      headStyles: {
        fillColor: BRAND,
        textColor: 255,
        fontStyle: "bold",
        fontSize: 9,
        cellPadding: 3.5,
      },
      alternateRowStyles: { fillColor: LIGHT_BG },
      tableLineColor: [210, 225, 235],
      tableLineWidth: 0.2,
      margin: { left: 14, right: 14, top: HEADER_H + 4, bottom: 14 },
      didDrawPage: (_hookData) => {
        drawPageHeader();
      },
    });

    y = (doc as any).lastAutoTable.finalY + 12;
  }

  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...GRAY);
    doc.text(
      `Generated by FinVision360 · ${new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}`,
      14,
      pageH - 5
    );
    doc.text(
      `Page ${p} of ${totalPages}`,
      pageW - 14,
      pageH - 5,
      { align: "right" }
    );
    doc.setDrawColor(...GRAY);
    doc.setLineWidth(0.3);
    doc.line(14, pageH - 9, pageW - 14, pageH - 9);
  }

  doc.save(`${data.filename}.pdf`);
}

function quoteCell(value: string): string {
  if (value.includes(",") || value.includes('"') || value.includes("\n")) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

function download(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
