import type { InsertAssetTypeList, InsertLiabilitiesTypeList } from "@shared/schema";

export const assetTypeListSeedData: InsertAssetTypeList[] = [
  {
    type: "Asset",
    parentCategory: "Cash & Banking",
    subCategory: "Checking Account",
    description: "Daily transactional accounts.",
    rateOfReturn: "0",
    rateOfReturnInflationAdjusted: "-0.025",
  },
  {
    type: "Asset",
    parentCategory: "Cash & Banking",
    subCategory: "Savings Account",
    description: "Standard or high-yield savings (HYSA).",
    rateOfReturn: "0.03",
    rateOfReturnInflationAdjusted: "0.005",
  },
  {
    type: "Asset",
    parentCategory: "Cash & Banking",
    subCategory: "Cash & Digital Wallets",
    description: "Physical currency or wallet balances.",
    rateOfReturn: "0",
    rateOfReturnInflationAdjusted: "-0.025",
  },
  {
    type: "Asset",
    parentCategory: "Cash & Banking",
    subCategory: "Certificates of Deposit (CDs)",
    description: "Fixed-term savings vehicles.",
    rateOfReturn: "0.03",
    rateOfReturnInflationAdjusted: "0.005",
  },
  {
    type: "Asset",
    parentCategory: "Market Investments",
    subCategory: "Stocks, ETFs, Mutual fund",
    description: "Stocks, ETFs, mutual funds, and options.",
    rateOfReturn: "0.095",
    rateOfReturnInflationAdjusted: "0.07",
  },
  {
    type: "Asset",
    parentCategory: "Market Investments",
    subCategory: "Fixed Income (Bonds & Treasury)",
    description: "Bonds, Treasury",
    rateOfReturn: "0.045",
    rateOfReturnInflationAdjusted: "0.02",
  },
  {
    type: "Asset",
    parentCategory: "Market Investments",
    subCategory: "Crypto & Digital Asset",
    description: "Bitcoin, Ethereum, and other tokens.",
    rateOfReturn: "0",
    rateOfReturnInflationAdjusted: "0",
  },
  {
    type: "Asset",
    parentCategory: "Market Investments",
    subCategory: "Precious Metal / Commodities",
    description: "Gold, silver, or commodity contracts.",
    rateOfReturn: "0.03",
    rateOfReturnInflationAdjusted: "0.005",
  },
  {
    type: "Asset",
    parentCategory: "Retirement & Tax-Advantaged",
    subCategory: "Employer Retirement",
    description: "401(k), 403(b), or TSP accounts.",
    rateOfReturn: "0.085",
    rateOfReturnInflationAdjusted: "0.06",
  },
  {
    type: "Asset",
    parentCategory: "Retirement & Tax-Advantaged",
    subCategory: "Individual Retirement",
    description: "Traditional IRA, Roth IRA, or SEP IRA.",
    rateOfReturn: "0.085",
    rateOfReturnInflationAdjusted: "0.06",
  },
  {
    type: "Asset",
    parentCategory: "Retirement & Tax-Advantaged",
    subCategory: "Health Savings (HSA)",
    description: "Quadruple tax-advantaged investment funds.",
    rateOfReturn: "0.085",
    rateOfReturnInflationAdjusted: "0.06",
  },
  {
    type: "Asset",
    parentCategory: "Retirement & Tax-Advantaged",
    subCategory: "Education Savings",
    description: "529 plans or Coverdell accounts.",
    rateOfReturn: "0.065",
    rateOfReturnInflationAdjusted: "0.04",
  },
  {
    type: "Asset",
    parentCategory: "Real Estate & Property",
    subCategory: "Primary Residence",
    description: "The user's main home.",
    rateOfReturn: "0.04",
    rateOfReturnInflationAdjusted: "0.015",
  },
  {
    type: "Asset",
    parentCategory: "Real Estate & Property",
    subCategory: "Personal Property",
    description: "Secondary homes or  vacation properties, land or other personal real estate",
    rateOfReturn: "0.04",
    rateOfReturnInflationAdjusted: "0.015",
  },
  {
    type: "Asset",
    parentCategory: "Real Estate & Property",
    subCategory: "Investment Property",
    description: "Rental units, commercial real estate, or land.",
    rateOfReturn: "0.055",
    rateOfReturnInflationAdjusted: "0.03",
  },
  {
    type: "Asset",
    parentCategory: "Real Estate & Property",
    subCategory: "Vehicles & Transport",
    description: "Cars, trucks, boats, or powersports.",
    rateOfReturn: "-0.12",
    rateOfReturnInflationAdjusted: "-0.145",
  },
  {
    type: "Asset",
    parentCategory: "Private Business & Alternatives",
    subCategory: "Business Equity",
    description: "Private business valuation, startups, or LLC stakes.",
    rateOfReturn: "0",
    rateOfReturnInflationAdjusted: "0",
  },
  {
    type: "Asset",
    parentCategory: "Private Business & Alternatives",
    subCategory: "Alternative Collectibles",
    description: "Art, watches, wine, sneakers, or trading cards.",
    rateOfReturn: "0.025",
    rateOfReturnInflationAdjusted: "0",
  },
  {
    type: "Asset",
    parentCategory: "Private Business & Alternatives",
    subCategory: "Life Insurance",
    description: "Life Insurance Cash Values",
    rateOfReturn: "0.045",
    rateOfReturnInflationAdjusted: "0.02",
  },
  {
    type: "Asset",
    parentCategory: "Other Assets",
    subCategory: "Miscellaneous Assets",
    description: "Assets not in any of the listed categories",
    rateOfReturn: "0.025",
    rateOfReturnInflationAdjusted: "0",
  },
];

export const liabilitiesTypeListSeedData: InsertLiabilitiesTypeList[] = [
  {
    type: "Liability",
    parentCategory: "Revolving Credit",
    subCategory: "Credit Cards",
    description: "Standard bank, store, or rewards credit cards.",
  },
  {
    type: "Liability",
    parentCategory: "Revolving Credit",
    subCategory: "Lines of Credit (LOC)",
    description: "Unsecured personal lines of credit.",
  },
  {
    type: "Liability",
    parentCategory: "Revolving Credit",
    subCategory: "Overdraft Protection",
    description: "Linked banking lines used for short-term liquidity.",
  },
  {
    type: "Liability",
    parentCategory: "Personal & Consumer Loans",
    subCategory: "Personal Loans",
    description: "Unsecured fixed-term loans.",
  },
  {
    type: "Liability",
    parentCategory: "Personal & Consumer Loans",
    subCategory: "Auto Loans",
    description: "Secured loans for cars, trucks, or motorcycles.",
  },
  {
    type: "Liability",
    parentCategory: "Personal & Consumer Loans",
    subCategory: "Leases",
    description: "Auto, equipment, or machinery lease commitments.",
  },
  {
    type: "Liability",
    parentCategory: "Personal & Consumer Loans",
    subCategory: "Buy Now, Pay Later (BNPL)",
    description: "Short-term point-of-sale installment plans.",
  },
  {
    type: "Liability",
    parentCategory: "Personal & Consumer Loans",
    subCategory: "Payday Loans",
    description: "High-interest, ultra-short-term cash advances typically secured by an upcoming paycheck or vehicle title",
  },
  {
    type: "Liability",
    parentCategory: "Real Estate Debt",
    subCategory: "Primary Mortgage",
    description: "First mortgage on the user's main residence.",
  },
  {
    type: "Liability",
    parentCategory: "Real Estate Debt",
    subCategory: "Secondary Mortgage",
    description: "Second liens, vacation home, or investment property loans.",
  },
  {
    type: "Liability",
    parentCategory: "Real Estate Debt",
    subCategory: "Home Equity (HELOC / HEL)",
    description: "Lines of credit or loans secured by home equity.",
  },
  {
    type: "Liability",
    parentCategory: "Education & Student Loans",
    subCategory: "Student Loans",
    description: "Government-backed or bank or private student debt.",
  },
  {
    type: "Liability",
    parentCategory: "Institutional & Custom Liabilities",
    subCategory: "Tax Debt",
    description: "Back taxes owed to authorities.",
  },
  {
    type: "Liability",
    parentCategory: "Institutional & Custom Liabilities",
    subCategory: "Medical Debt",
    description: "Unpaid healthcare, hospital, or provider balances.",
  },
  {
    type: "Liability",
    parentCategory: "Institutional & Custom Liabilities",
    subCategory: "Private Debt (IOUs)",
    description: "Money owed to friends, family, or individuals.",
  },
  {
    type: "Liability",
    parentCategory: "Institutional & Custom Liabilities",
    subCategory: "Business Loan",
    description: "Loan for business and guareenties",
  },
  {
    type: "Liability",
    parentCategory: "Institutional & Custom Liabilities",
    subCategory: "Legal Obligations (Alimony/Child Support) ",
    description: "Mandatory court-ordered, recurring monthly financial commitments resulting from domestic relations or family law rulings.",
  },
  {
    type: "Liability",
    parentCategory: "Other",
    subCategory: "Other Liability",
    description: "Any liability not covered in above categories",
  },
];