import type { InsertTransactionTypeList } from "@shared/schema";

export const transactionTypeListSeedData: InsertTransactionTypeList[] = [
  { type: "Income", parentCategory: "Active Income", category: "Salary & Wages", needVsWant: null, description: "Regular employment paychecks and wages" },
  { type: "Income", parentCategory: "Active Income", category: "Business Income", needVsWant: null, description: "Income earned from business ownership or stake" },
  { type: "Income", parentCategory: "Active Income", category: "Bonuses & Commissions", needVsWant: null, description: "Job performance bonuses or sales commissions" },
  { type: "Income", parentCategory: "Active Income", category: "Freelance & Consulting", needVsWant: null, description: "1099 contract work gig economy side hustles" },
  { type: "Income", parentCategory: "Passive Income", category: "Dividends", needVsWant: null, description: "Stock dividend payouts" },
  { type: "Income", parentCategory: "Passive Income", category: "Interest", needVsWant: null, description: "High-yield savings or money market or CD interest" },
  { type: "Income", parentCategory: "Passive Income", category: "Rental Income", needVsWant: null, description: "Real estate investment rental revenue" },
  { type: "Income", parentCategory: "Passive Income", category: "Capital Gains", needVsWant: null, description: "Profits from selling assets or stocks" },
  { type: "Income", parentCategory: "Passive Income", category: "Royalties", needVsWant: null, description: "Music, book, patent/IP licensing, digital assets royalties" },
  { type: "Income", parentCategory: "Passive Income", category: "Crypto", needVsWant: null, description: "Staking rewards, liquidity pool rewards, yield farming rewards, mining rewards" },
  { type: "Income", parentCategory: "Other Income", category: "Tax Refunds", needVsWant: null, description: "Federal state or local tax refunds" },
  { type: "Income", parentCategory: "Other Income", category: "Gifts", needVsWant: null, description: "Cash gifts for birthdays holidays or events" },
  { type: "Income", parentCategory: "Other Income", category: "Grants & Scholarships", needVsWant: null, description: "Educational or business grant money" },
  { type: "Income", parentCategory: "Other Income", category: "Reimbursements / Cashbacks", needVsWant: null, description: "Work expense reimbursement, cashbacks or insurance payouts" },
  { type: "Income", parentCategory: "Other Income", category: "Refunds", needVsWant: null, description: "Money returned by a store or merchant for a canceled order, returned item, or booking cancellation" },
  { type: "Income", parentCategory: "Other Income", category: "Government Benefits", needVsWant: null, description: "Social security unemployment or subsidies" },
  { type: "Income", parentCategory: "Other Income", category: "Other Income", needVsWant: null, description: "Income not fitting in any of the listed categories" },
  { type: "Expense", parentCategory: "Housing and Utilities", category: "Housing / Rent", needVsWant: "Need", description: "Monthly rent or mortgage payments" },
  { type: "Expense", parentCategory: "Housing and Utilities", category: "Utilities", needVsWant: "Need", description: "Electricity, water, gas, internet, phone" },
  { type: "Expense", parentCategory: "Housing and Utilities", category: "Home Maintenance/Repairs", needVsWant: "Need", description: "Home maintenance or repair costs" },
  { type: "Expense", parentCategory: "Food & Lifestyle", category: "Groceries", needVsWant: "Need", description: "Food and household essentials" },
  { type: "Expense", parentCategory: "Food & Lifestyle", category: "Dining Out", needVsWant: "Want", description: "Restaurants, cafes, takeout" },
  { type: "Expense", parentCategory: "Food & Lifestyle", category: "Entertainment", needVsWant: "Want", description: "Movies, events, streaming, outings" },
  { type: "Expense", parentCategory: "Food & Lifestyle", category: "Personal Care", needVsWant: "Want", description: "Salon, grooming, cosmetics" },
  { type: "Expense", parentCategory: "Food & Lifestyle", category: "Pets", needVsWant: "Want", description: "Pet food, vet bills, grooming" },
  { type: "Expense", parentCategory: "Health & Wellness", category: "Healthcare", needVsWant: "Need", description: "Medical bills, prescriptions, doctor visits" },
  { type: "Expense", parentCategory: "Health & Wellness", category: "Insurance", needVsWant: "Need", description: "Health, auto, home, life insurance premiums" },
  { type: "Expense", parentCategory: "Family & Community", category: "Education", needVsWant: "Need", description: "Tuition, books, courses, school supplies" },
  { type: "Expense", parentCategory: "Shopping", category: "Shopping", needVsWant: "Want", description: "Clothing, electronics, household items" },
  { type: "Expense", parentCategory: "Transportation", category: "Transportation", needVsWant: "Need", description: "Fuel, auto maintenance, public transit, parking, tolls" },
  { type: "Expense", parentCategory: "Transportation", category: "Travel", needVsWant: "Want", description: "Flights, hotels, vacations" },
  { type: "Expense", parentCategory: "Financial / Obligations", category: "Debt Payment", needVsWant: "Need", description: "Loan payments: credit card, auto, student, personal loans" },
  { type: "Expense", parentCategory: "Financial & Obligations", category: "Professional Services", needVsWant: "Need", description: "Fees paid to licensed or specialized professionals such as lawyers, accountants, financial advisors, consultants, and other expert service providers" },
  { type: "Expense", parentCategory: "Financial & Obligations", category: "Taxes", needVsWant: "Need", description: "Property tax, estimated tax payments, other taxes" },
  { type: "Expense", parentCategory: "Financial & Obligations", category: "Fees & Interest Charges", needVsWant: "Need", description: "Bank fees, overdraft fees, ATM fees, and credit card interest charges" },
  { type: "Expense", parentCategory: "Family & Community", category: "Childcare", needVsWant: "Need", description: "Care services for children including daycare, babysitting, after-school programs, nannies, and early childhood education fees." },
  { type: "Expense", parentCategory: "Family & Community", category: "Gifts Given", needVsWant: "Want", description: "Gifts for birthdays, holidays, celebrations" },
  { type: "Expense", parentCategory: "Family & Community", category: "Donations", needVsWant: "Want", description: "Charitable donations and contributions" },
  { type: "Expense", parentCategory: "Family & Community", category: "Alimony & Support", needVsWant: "Need", description: "Child support, alimony, dependent support" },
  { type: "Expense", parentCategory: "Other Expense", category: "Other Expense", needVsWant: "Want", description: "General expenses not fitting other categories" },
  { type: "Transfer", parentCategory: "Internal Transfer", category: "Investment", needVsWant: null, description: "Brokerage deposits, crypto purchases, investment contributions" },
  { type: "Transfer", parentCategory: "Internal Transfer", category: "Savings", needVsWant: null, description: "Savings transfers, emergency fund contributions" },
  { type: "Transfer", parentCategory: "Internal Transfer", category: "Credit card Payments", needVsWant: null, description: "Payment made to credit cards" },
  { type: "Transfer", parentCategory: "Internal Transfer", category: "Other", needVsWant: null, description: "Other between account money movement" },
];