uploads = []
outputs = []

[[generated]]
id = "T_tT94PvpKL6dnz4Hr-uS"
uri = "file://client/public/images/dashboard-abstract.png"
type = "image"
title = "abstract financial dashboard UI"

[[generated]]
id = "pHnDennJS7RXpyNEhvbHl"
uri = "file://client/public/images/retirement-abstract.png"
type = "image"
title = "abstract retirement chart"

[[generated]]
id = "Qx15kOis3V-wipNVAt4-h"
uri = "file://client/public/images/ai-abstract.png"
type = "image"
title = "abstract AI brain core"
